{
  try {
    future.get(2,TimeUnit.SECONDS);
    fail("Exception expected");
  }
 catch (  Exception e) {
    assertThat(e,instanceOf(TimeoutException.class));
  }
}
