{
  try {
    constraintCreation.get();
  }
 catch (  ExecutionException e) {
    assertThat(e.getCause(),instanceOf(ConstraintViolationException.class));
    constraintViolation.get();
  }
  try {
    constraintViolation.get();
    fail("Constraint violating operations succeeded, even though they were violating a successfully created constraint.");
  }
 catch (  ExecutionException e) {
    assertThat(e.getCause(),instanceOf(TransactionFailureException.class));
    assertAllPropertiesAreUnique(master,label,property);
  }
}
