{
  try {
    testCallEmpty(db,subject,call,null);
    fail("Expected exception to be thrown");
  }
 catch (  Exception e) {
    assertEquals(expectedExceptionClass,e.getClass());
    assertTrue("Exception should contain '" + partOfErrorMsg + "'",e.getMessage().contains(partOfErrorMsg));
  }
}
