{
  CompletableFuture<Integer> future=new CompletableFuture<>();
  future.cancel(false);
  assertThat(future.isDone(),is(true));
  assertThat(future.isCancelled(),is(true));
  try {
    future.get();
    fail("expected exception not thrown");
  }
 catch (  CancellationException e) {
  }
}
