{
  try {
    txFuture.get();
    fail("Exception expected");
  }
 catch (  ExecutionException e) {
    assertThat(e.getCause(),instanceOf(TransactionTerminatedException.class));
  }
}
