{
  try {
    f.apply();
    fail("Expected exception of type " + typeOfException + ", but no exception was thrown");
  }
 catch (  Exception e) {
    if (typeOfException.isInstance(e)) {
      assertThat(e.getMessage(),containsString(partOfErrorMessage));
    }
 else {
      fail("Got unexpected exception " + e.getClass() + "\nExpected: "+ typeOfException);
    }
  }
}
