{
  long txId=3;
  String failureMessage="Forces a failure";
  WritableLogChannel channel=spy(new InMemoryLogChannel());
  IOException failure=new IOException(failureMessage);
  when(channel.putInt(anyInt())).thenThrow(failure);
  LogFile logFile=mock(LogFile.class);
  when(logFile.getWriter()).thenReturn(channel);
  TransactionMetadataCache metadataCache=new TransactionMetadataCache(10,10);
  TransactionIdStore transactionIdStore=mock(TransactionIdStore.class);
  when(transactionIdStore.nextCommittingTransactionId()).thenReturn(txId);
  Mockito.reset(kernelHealth);
  TransactionAppender appender=life.add(new BatchingTransactionAppender(logFile,NO_ROTATION,metadataCache,transactionIdStore,BYPASS,kernelHealth));
  life.start();
  TransactionRepresentation transaction=mock(TransactionRepresentation.class);
  when(transaction.additionalHeader()).thenReturn(new byte[0]);
  try {
    appender.append(transaction,logAppendEvent);
    fail("Expected append to fail. Something is wrong with the test itself");
  }
 catch (  IOException e) {
    assertTrue(contains(e,failureMessage,IOException.class));
    verify(transactionIdStore,times(1)).nextCommittingTransactionId();
    verify(transactionIdStore,times(1)).transactionClosed(txId);
    verify(kernelHealth).panic(failure);
  }
}
